# Scratch

#### - Run a Python File

In [1]:
# Run "hello.py"

%run hello.py

Hello, World!

#### - Use "argparser"

In [2]:
# Run "hello_argparse.py" without any designations

%run hello_argparse.py

Hello, World!
RESULT : 102.4

In [3]:
# Run "hello_argparse.py" by designating the following arguments

%run hello_argparse.py --display --alpha 0.3 --text "Hello, argparse!" --num_iters 5

Hello, argparse!
0.6
1.2
2.4
4.8
9.6
RESULT : 9.6

## [Task 1] Create "train_test_split" of scikit-learn from Scratch

In [4]:
# Add a path searching for specific modules

import sys

sys.path.append("../scratch/utils/")

In [5]:
# Check the addition

sys.path

['/Users/kazukiegusa/.pyenv/versions/anaconda3-5.3.0/lib/python36.zip',
 '/Users/kazukiegusa/.pyenv/versions/anaconda3-5.3.0/lib/python3.6',
 '/Users/kazukiegusa/.pyenv/versions/anaconda3-5.3.0/lib/python3.6/lib-dynload',
 '',
 '/Users/kazukiegusa/.pyenv/versions/anaconda3-5.3.0/lib/python3.6/site-packages',
 '/Users/kazukiegusa/.pyenv/versions/anaconda3-5.3.0/lib/python3.6/site-packages/aeosa',
 '/Users/kazukiegusa/.pyenv/versions/anaconda3-5.3.0/lib/python3.6/site-packages/IPython/extensions',
 '/Users/kazukiegusa/.ipython',
 '../scratch/utils/']

In [6]:
# Import "train_test_split" created from scratch

from split import train_test_split

In [7]:
# Split train and test datasets by taking an example

import numpy as np

X, y = np.arange(10).reshape((5, 2)), range(5)

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7)

In [8]:
# Validate the split

X_train

array([[4, 5],
       [2, 3],
       [8, 9],
       [6, 7]])

In [9]:
X_test

array([0, 1])

In [10]:
y_train

array([3, 0, 4, 2])

In [11]:
y_test

array([1])

# Create Pipelines

## [Task 2] Create Classification Pipelines

<br />

I am going to use logistic regression, SVM and decition tree, and prepare for 3 kinds of datasets.

#### - First Dataset

<br />

The first dataset is iris datasets. I use only 2 objective variables, versicolor and virginica, to make this task to a binary classification.

In [12]:
# Import the dataset

from sklearn.datasets import load_iris

iris = load_iris()

iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== ==== ======= ===== ====================\n\n    :Missing Attribute Values: None\n    :Class Distribution: 33.3% for each of 3 classes.\n    :Creator: R.A. Fisher\n    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n    :Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. topic:: References\n\n   - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n     Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n     Mathematical Statistics" (John Wiley, NY, 1950).\n   - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n     (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n   - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n     Structure and Classification Rule for Recognition in Partially Exposed\n     Environments".  IEEE Transactions on Pattern Analysis and Machine\n     Intelligence, Vol. PAMI-2, No. 1, 67-71.\n   - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n     on Information Theory, May 1972, 431-433.\n   - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n     conceptual clustering system finds 3 classes in the data.\n   - Many, many more ...',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': '/Users/kazukiegusa/.pyenv/versions/anaconda3-5.3.0/lib/python3.6/site-packages/sklearn/datasets/data/iris.csv'}

In [13]:
# Create a dataframe

import pandas as pd

X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = pd.DataFrame(iris.target, columns=["Species"])

Xy = pd.concat([X,y], axis=1)

df = Xy[Xy.Species!=0]

df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Species
50,7.0,3.2,4.7,1.4,1
51,6.4,3.2,4.5,1.5,1
52,6.9,3.1,4.9,1.5,1
53,5.5,2.3,4.0,1.3,1
54,6.5,2.8,4.6,1.5,1
55,5.7,2.8,4.5,1.3,1
56,6.3,3.3,4.7,1.6,1
57,4.9,2.4,3.3,1.0,1
58,6.6,2.9,4.6,1.3,1
59,5.2,2.7,3.9,1.4,1
60,5.0,2.0,3.5,1.0,1
61,5.9,3.0,4.2,1.5,1
62,6.0,2.2,4.0,1.0,1
63,6.1,2.9,4.7,1.4,1
64,5.6,2.9,3.6,1.3,1
65,6.7,3.1,4.4,1.4,1
66,5.6,3.0,4.5,1.5,1
67,5.8,2.7,4.1,1.0,1
68,6.2,2.2,4.5,1.5,1
69,5.6,2.5,3.9,1.1,1
70,5.9,3.2,4.8,1.8,1
71,6.1,2.8,4.0,1.3,1
72,6.3,2.5,4.9,1.5,1
73,6.1,2.8,4.7,1.2,1
74,6.4,2.9,4.3,1.3,1
75,6.6,3.0,4.4,1.4,1
76,6.8,2.8,4.8,1.4,1
77,6.7,3.0,5.0,1.7,1
78,6.0,2.9,4.5,1.5,1
79,5.7,2.6,3.5,1.0,1
...,...,...,...,...,...
120,6.9,3.2,5.7,2.3,2
121,5.6,2.8,4.9,2.0,2
122,7.7,2.8,6.7,2.0,2
123,6.3,2.7,4.9,1.8,2
124,6.7,3.3,5.7,2.1,2
125,7.2,3.2,6.0,1.8,2
126,6.2,2.8,4.8,1.8,2
127,6.1,3.0,4.9,1.8,2
128,6.4,2.8,5.6,2.1,2
129,7.2,3.0,5.8,1.6,2
130,7.4,2.8,6.1,1.9,2
131,7.9,3.8,6.4,2.0,2
132,6.4,2.8,5.6,2.2,2
133,6.3,2.8,5.1,1.5,2
134,6.1,2.6,5.6,1.4,2
135,7.7,3.0,6.1,2.3,2
136,6.3,3.4,5.6,2.4,2
137,6.4,3.1,5.5,1.8,2
138,6.0,3.0,4.8,1.8,2
139,6.9,3.1,5.4,2.1,2
140,6.7,3.1,5.6,2.4,2
141,6.9,3.1,5.1,2.3,2
142,5.8,2.7,5.1,1.9,2
143,6.8,3.2,5.9,2.3,2
144,6.7,3.3,5.7,2.5,2
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [14]:
# create and save a csv file of the dataframe

df.to_csv('iris_dataset.csv')

#### - Second Dataset

In [15]:
# Create a dataset by myself and change it to a dataframe

np.random.seed(seed=0)
n_samples = 500
f0 = [-1, 2]
f1 = [2, -1]
cov = [[1.0,0.8], [0.8, 1.0]]

f0 = np.random.multivariate_normal(f0, cov, int(n_samples/2))
f1 = np.random.multivariate_normal(f1, cov, int(n_samples/2))

X = np.concatenate((f0, f1))
y = np.concatenate((np.ones((int(n_samples/2))), np.ones((int(n_samples/2)))*(-1))).astype(np.int)

random_index = np.random.permutation(np.arange(n_samples))
X = X[random_index]
y = y[random_index]

df2 = pd.concat([pd.DataFrame(X,columns=["explanatory variable 1","explanatory variable 2"]), 
                 pd.DataFrame(y,columns=["objective variable"])], axis=1)

df2

     explanatory variable 1  explanatory variable 2  objective variable
0                  0.772383               -2.291673                  -1
1                 -0.593349                1.667883                   1
2                 -2.076486                0.487468                   1
3                  0.119227                3.625380                   1
4                 -3.130006               -0.156732                   1
5                 -1.781098                1.222249                   1
6                  3.997710                1.251640                  -1
7                  2.156045               -0.385824                  -1
8                  1.947416               -1.296390                  -1
9                  1.587574               -1.859892                  -1
10                 2.053690               -0.947186                  -1
11                -1.974394                1.227187                   1
12                -3.474873                0.370421                   1
13                 1.680950               -0.636508                  -1
14                -0.951997                1.419896                   1
15                -1.230543                2.488490                   1
16                -0.696789                1.883590                   1
17                 1.038425               -0.888816                  -1
18                 3.687065                0.430243                  -1
19                -1.030029                1.278659                   1
20                -1.266582                1.972589                   1
21                -0.019764                2.544127                   1
22                 0.860592               -2.461861                  -1
23                 1.188950               -0.880504                  -1
24                -1.875750                1.563648                   1
25                 2.461655               -2.006018                  -1
26                -1.598482                1.106529                   1
27                 3.987446               -0.136849                  -1
28                -0.999509                2.508009                   1
29                 2.178234               -1.069193                  -1
..                      ...                     ...                 ...
470               -1.690444                0.528583                   1
471               -0.391383                3.374612                   1
472                2.629979               -1.420340                  -1
473                1.674837               -1.559325                  -1
474               -2.964095                0.664816                   1
475               -0.955963                1.072431                   1
476                2.480737               -1.353090                  -1
477               -0.176846                1.763157                   1
478                3.519585                0.037924                  -1
479                1.683407               -1.108121                  -1
480               -1.285871                3.239899                   1
481                4.044625                0.053081                  -1
482               -0.672809                1.897009                   1
483                1.647736               -1.373920                  -1
484               -0.875886                3.173706                   1
485                2.453720               -0.116226                  -1
486                2.491749                0.278093                  -1
487                0.377129               -2.706981                  -1
488                1.546347               -1.213803                  -1
489                2.302993               -0.441960                  -1
490               -0.258877                3.259894                   1
491                0.001821                4.235599                   1
492                1.297671               -0.645532                  -1
493                2.160441               -0.149708                  -1
494                1.665733               -2.031806                  -1
495                1.248144               -2.167980                  -1
496               -2.610585                0.739247                   1
497                0.317317                2.225520                   1
498               -1.359196                0.892052                   1
499                1.102983               -0.548525                  -1

[500 rows x 3 columns]

In [16]:
# create and save a csv file of the dataframe

df2.to_csv('simple_dataset1.csv')

#### - Third Dataset

In [17]:
# Create a dataset by myself and change it to a dataframe

X = np.array([[-0.44699 , -2.8073  ],[-1.4621  , -2.4586  ],
              [ 0.10645 ,  1.9242  ],[-3.5944  , -4.0112  ],
              [-0.9888  ,  4.5718  ],[-3.1625  , -3.9606  ],
              [ 0.56421 ,  0.72888 ],[-0.60216 ,  8.4636  ],
              [-0.61251 , -0.75345 ],[-0.73535 , -2.2718  ],
              [-0.80647 , -2.2135  ],[ 0.86291 ,  2.3946  ],
              [-3.1108  ,  0.15394 ],[-2.9362  ,  2.5462  ],
              [-0.57242 , -2.9915  ],[ 1.4771  ,  3.4896  ],
              [ 0.58619 ,  0.37158 ],[ 0.6017  ,  4.3439  ],
              [-2.1086  ,  8.3428  ],[-4.1013  , -4.353   ],
              [-1.9948  , -1.3927  ],[ 0.35084 , -0.031994],
              [ 0.96765 ,  7.8929  ],[-1.281   , 15.6824  ],
              [ 0.96765 , 10.083   ],[ 1.3763  ,  1.3347  ],
              [-2.234   , -2.5323  ],[-2.9452  , -1.8219  ],
              [ 0.14654 , -0.28733 ],[ 0.5461  ,  5.8245  ],
              [-0.65259 ,  9.3444  ],[ 0.59912 ,  5.3524  ],
              [ 0.50214 , -0.31818 ],[-3.0603  , -3.6461  ],
              [-6.6797  ,  0.67661 ],[-2.353   , -0.72261 ],
              [ 1.1319  ,  2.4023  ],[-0.12243 ,  9.0162  ],
              [-2.5677  , 13.1779  ],[ 0.057313,  5.4681  ]])

y = np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1])

df3 = pd.concat([pd.DataFrame(X,columns=["explanatory variable 1","explanatory variable 2"]), 
                 pd.DataFrame(y,columns=["objective variable"])], axis=1)

df3

    explanatory variable 1  explanatory variable 2  objective variable
0                -0.446990               -2.807300                   0
1                -1.462100               -2.458600                   0
2                 0.106450                1.924200                   0
3                -3.594400               -4.011200                   0
4                -0.988800                4.571800                   0
5                -3.162500               -3.960600                   0
6                 0.564210                0.728880                   0
7                -0.602160                8.463600                   0
8                -0.612510               -0.753450                   0
9                -0.735350               -2.271800                   0
10               -0.806470               -2.213500                   0
11                0.862910                2.394600                   0
12               -3.110800                0.153940                   0
13               -2.936200                2.546200                   0
14               -0.572420               -2.991500                   0
15                1.477100                3.489600                   0
16                0.586190                0.371580                   0
17                0.601700                4.343900                   0
18               -2.108600                8.342800                   0
19               -4.101300               -4.353000                   0
20               -1.994800               -1.392700                   1
21                0.350840               -0.031994                   1
22                0.967650                7.892900                   1
23               -1.281000               15.682400                   1
24                0.967650               10.083000                   1
25                1.376300                1.334700                   1
26               -2.234000               -2.532300                   1
27               -2.945200               -1.821900                   1
28                0.146540               -0.287330                   1
29                0.546100                5.824500                   1
30               -0.652590                9.344400                   1
31                0.599120                5.352400                   1
32                0.502140               -0.318180                   1
33               -3.060300               -3.646100                   1
34               -6.679700                0.676610                   1
35               -2.353000               -0.722610                   1
36                1.131900                2.402300                   1
37               -0.122430                9.016200                   1
38               -2.567700               13.177900                   1
39                0.057313                5.468100                   1

In [18]:
# create and save a csv file of the dataframe

df3.to_csv('simple_dataset2.csv')

#### Validate the Classification Pipeline

In [19]:
# validate the classification pipeline on the iris dataset by logistic regression

%run ../scratch/model/classification_pipeline.py --dataset "/Users/kazukiegusa/git-dic/dic/ml/sprint2/iris_dataset.csv" --model "lr"

y_pred is [2 2 2 2 2 1 2 1 1 1 1 2 1 1 2 2 2 1 2 1]
score is 1.0

/Users/kazukiegusa/.pyenv/versions/anaconda3-5.3.0/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

In [20]:
# iris_dataset by svm

%run ../scratch/model/classification_pipeline.py --dataset "/Users/kazukiegusa/git-dic/dic/ml/sprint2/iris_dataset.csv" --model "svm"

y_pred is [2 1 1 1 1 2 2 1 2 1 1 1 1 2 2 1 1 2 1 2]
score is 1.0

/Users/kazukiegusa/.pyenv/versions/anaconda3-5.3.0/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

In [21]:
# iris_dataset by decition tree
%run ../scratch/model/classification_pipeline.py --dataset "/Users/kazukiegusa/git-dic/dic/ml/sprint2/iris_dataset.csv" --model "dt"

y_pred is [2 2 1 1 1 1 1 2 1 1 1 2 2 2 2 1 1 1 1 2]
score is 1.0

/Users/kazukiegusa/.pyenv/versions/anaconda3-5.3.0/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

In [22]:
# simple_dataset1 by logistic regression
%run ../scratch/model/classification_pipeline.py --dataset "/Users/kazukiegusa/git-dic/dic/ml/sprint2/simple_dataset1.csv" --model "lr"

y_pred is [ 1 -1  1  1  1 -1  1  1  1  1  1 -1  1  1 -1 -1 -1  1  1 -1  1  1  1  1
 -1  1 -1 -1 -1  1 -1  1 -1  1 -1  1 -1  1  1  1  1 -1  1  1  1 -1  1  1
  1  1 -1 -1 -1  1 -1 -1 -1  1 -1  1  1 -1  1 -1 -1  1  1  1 -1  1 -1 -1
  1  1  1 -1 -1  1 -1 -1 -1  1  1  1 -1 -1 -1 -1  1  1  1 -1 -1  1  1  1
 -1  1 -1 -1]
score is 1.0

/Users/kazukiegusa/.pyenv/versions/anaconda3-5.3.0/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

In [23]:
# simple_dataset1 by svm
%run ../scratch/model/classification_pipeline.py --dataset "/Users/kazukiegusa/git-dic/dic/ml/sprint2/simple_dataset1.csv" --model "svm"

y_pred is [ 1 -1 -1  1 -1  1  1  1  1  1  1 -1 -1 -1 -1  1 -1  1 -1 -1  1 -1  1  1
 -1 -1  1 -1  1  1 -1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1 -1  1
  1  1  1  1  1 -1 -1 -1  1  1 -1  1  1  1 -1 -1 -1  1 -1  1 -1 -1  1 -1
 -1 -1  1  1 -1 -1  1  1 -1  1  1  1  1 -1 -1 -1  1  1  1  1  1  1 -1  1
 -1  1 -1 -1]
score is 0.85

/Users/kazukiegusa/.pyenv/versions/anaconda3-5.3.0/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

## [Task 3] Create Regression Pipelines

<br />

I am going to create a pipeline of linear regression that can run python files.

In [24]:
# Import the dataset

train = pd.read_csv('"House Prices- Advanced Regression Techniques".train.csv')

train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000
10,11,20,RL,70.0,11200,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,129500
11,12,60,RL,85.0,11924,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,New,Partial,345000
12,13,20,RL,NaN,12968,Pave,NaN,IR2,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,144000
13,14,20,RL,91.0,10652,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,New,Partial,279500
14,15,20,RL,NaN,10920,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,GdWo,NaN,0,5,2008,WD,Normal,157000
15,16,45,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,7,2007,WD,Normal,132000
16,17,20,RL,NaN,11241,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,700,3,2010,WD,Normal,149000
17,18,90,RL,72.0,10791,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,Shed,500,10,2006,WD,Normal,90000
18,19,20,RL,66.0,13695,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,159000
19,20,20,RL,70.0,7560,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,5,2009,COD,Abnorml,139000
20,21,60,RL,101.0,14215,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,New,Partial,325300
21,22,45,RM,57.0,7449,Pave,Grvl,Reg,Bnk,AllPub,...,0,NaN,GdPrv,NaN,0,6,2007,WD,Normal,139400
22,23,20,RL,75.0,9742,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,230000
23,24,120,RM,44.0,4224,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2007,WD,Normal,129900
24,25,20,RL,NaN,8246,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,5,2010,WD,Normal,154000
25,26,20,RL,110.0,14230,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2009,WD,Normal,256300
26,27,20,RL,60.0,7200,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,134800
27,28,20,RL,98.0,11478,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,306000
28,29,20,RL,47.0,16321,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2006,WD,Normal,207500
29,30,30,RM,60.0,6324,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,68500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,1431,60,RL,60.0,21930,Pave,NaN,IR3,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Normal,192140
1431,1432,120,RL,NaN,4928,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2009,WD,Normal,143750
1432,1433,30,RL,60.0,10800,Pave,Grvl,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,64500
1433,1434,60,RL,93.0,10261,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,186500
1434,1435,20,RL,80.0,17400,Pave,NaN,Reg,Low,AllPub,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,160000
1435,1436,20,RL,80.0,8400,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,7,2008,COD,Abnorml,174000
1436,1437,20,RL,60.0,9000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdWo,NaN,0,5,2007,WD,Normal,120500
1437,1438,20,RL,96.0,12444,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2008,New,Partial,394617
1438,1439,20,RM,90.0,7407,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,4,2010,WD,Normal,149700
1439,1440,60,RL,80.0,11584,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2007,WD,Normal,197000
1440,1441,70,RL,79.0,11526,Pave,NaN,IR1,Bnk,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,191000
1441,1442,120,RM,NaN,4426,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,149300
1442,1443,60,FV,85.0,11003,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2009,WD,Normal,310000
1443,1444,30,RL,NaN,8854,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,121000
1444,1445,20,RL,63.0,8500,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2007,WD,Normal,179600
1445,1446,85,RL,70.0,8400,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,129000
1446,1447,20,RL,NaN,26142,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,157900
1447,1448,60,RL,80.0,10000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2007,WD,Normal,240000
1448,1449,50,RL,70.0,11767,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdWo,NaN,0,5,2007,WD,Normal,112000
1449,1450,180,RM,21.0,1533,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2006,WD,Abnorml,92000
1450,1451,90,RL,60.0,9000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2009,WD,Normal,136000
1451,1452,20,RL,78.0,9262,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,New,Partial,287090
1452,1453,180,RM,35.0,3675,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,145000
1453,1454,20,RL,90.0,17217,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Abnorml,84500
1454,1455,20,FV,62.0,7500,Pave,Pave,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2009,WD,Normal,185000
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [25]:
# Set the explanatory and objective variables and create a dataframe

X = train[["GrLivArea","YearBuilt"]]
y = train["SalePrice"]

df4 = pd.concat([X,y], axis=1)

df4

      GrLivArea  YearBuilt  SalePrice
0          1710       2003     208500
1          1262       1976     181500
2          1786       2001     223500
3          1717       1915     140000
4          2198       2000     250000
5          1362       1993     143000
6          1694       2004     307000
7          2090       1973     200000
8          1774       1931     129900
9          1077       1939     118000
10         1040       1965     129500
11         2324       2005     345000
12          912       1962     144000
13         1494       2006     279500
14         1253       1960     157000
15          854       1929     132000
16         1004       1970     149000
17         1296       1967      90000
18         1114       2004     159000
19         1339       1958     139000
20         2376       2005     325300
21         1108       1930     139400
22         1795       2002     230000
23         1060       1976     129900
24         1060       1968     154000
25         1600       2007     256300
26          900       1951     134800
27         1704       2007     306000
28         1600       1957     207500
29          520       1927      68500
...         ...        ...        ...
1430       1838       2005     192140
1431        958       1976     143750
1432        968       1927      64500
1433       1792       2000     186500
1434       1126       1977     160000
1435       1537       1962     174000
1436        864       1971     120500
1437       1932       2008     394617
1438       1236       1957     149700
1439       1725       1979     197000
1440       2555       1922     191000
1441        848       2004     149300
1442       2007       2008     310000
1443        952       1916     121000
1444       1422       2004     179600
1445        913       1966     129000
1446       1188       1962     157900
1447       2090       1995     240000
1448       1346       1910     112000
1449        630       1970      92000
1450       1792       1974     136000
1451       1578       2008     287090
1452       1072       2005     145000
1453       1140       2006      84500
1454       1221       2004     185000
1455       1647       1999     175000
1456       2073       1978     210000
1457       2340       1941     266500
1458       1078       1950     142125
1459       1256       1965     147500

[1460 rows x 3 columns]

In [26]:
# create and save a csv file of the dataframe

df4.to_csv('house_prices_dataset.csv')

In [28]:
# validate the regression pipeline

%run ../scratch/model/regression_pipeline.py --dataset "/Users/kazukiegusa/git-dic/dic/ml/sprint2/house_prices_dataset.csv" --model "lr"

y_pred is [113521.68191278 127915.8900842  118058.20989076 112114.57052089
 180362.27913489 122491.68851014 293107.24033852 214410.88558556
 145681.345614   137637.73867288 147358.4513156  242236.56243429
 235637.47687368 192718.13325497 292464.02012221 257410.76777566
 256386.16038465 225467.80675402 107397.35611657 260778.9950665
 163058.12793458  77476.64186021  62356.67664118 125273.32251764
 247542.01259416 154605.70750396 162791.9542418  132362.08256739
 126668.50675982 154165.59676212 196264.06576094 133920.09925087
 218470.93994029 136305.21898162 139583.60245553 151185.80963064
 121415.72643745 248374.82841142 130392.1359963  276953.83262133
 107626.98226993 247778.86647868 253160.95528983 170777.87271906
  97602.84001973 105615.89318    291282.5354329   97083.42564347
 231614.6435498   66626.63936755 119192.8739911  163155.35677705
 154481.0564057  113486.9946223  105545.2207113  245254.07465444
 253166.81256985 226373.882976   275497.3486676  236975.5809366
 182811.50057854 261939.75891022 104355.86119864 122858.968298
 224009.49346272 283096.0671095  119595.74584559  92855.54288859
 218928.01837369 224010.76570324 134271.81512936 159822.81210799
 210453.45921889 160284.3743622  288185.75161771 216102.70693022
 155313.57213495 194486.26074749 153588.04067571 192265.49405937
 125340.69134688 167395.64205579 187312.96417961 213963.51337711
 214293.60638085 131013.74593019 222142.76688898 309627.61164388
 141997.42170598 233807.70666628 144091.78390577 120515.65877372
 111129.3600981  478230.98285574 155771.95689196 262915.42636186
 261293.62682563 231754.32727124 219388.05647884 236043.90602098
 351905.17747242 213691.70920528 147615.22340391 155305.62926033
 156087.52339439 187689.75895824 176161.49768322 229741.92565754
 169658.19665888 159084.60983356 224218.07053845 226542.74572739
  79760.80188596 111054.20138889 271968.3518138  162528.66037791
 200575.74781136 192058.16145614 232826.06156777 215848.73069182
 229763.76896948 174092.60841082 241099.64314211 213603.72902138
 113634.23957106 185077.62426603 118818.51060611 155883.33812901
 116778.42508019 150324.36497702 268690.19946097 279555.91429676
 146459.80453853 206415.35329016 237047.07444323 226641.92892167
 177041.34667914 100706.7480913  156263.39099971 132282.60364683
  53946.01262577 148999.48184382 145370.64909178  65906.68564507
 180819.85749    144882.68265769 137703.02228353 235905.95715823
 148916.80259491 194542.16617321 253932.92388979 240989.31988821
 111360.93181978 223658.07901264 191215.68965743 138383.08811196
 182129.57412517 238156.89992403 143372.54043861 144617.11010531
 159890.65443132 115309.60590185 179156.18267573 122130.73184091
 151740.42021498 214597.56066997 103166.29548848 211264.57943436
 148892.37752679  92799.59041143 114473.08811812  84563.27452807
 112216.99419151 213631.01514626 238999.03825492 229313.73682966
 137242.63779095 172853.23880803 131792.37880045  91494.66278558
 143619.12901939 156262.72105601 292377.86513977 187111.06673384
 115532.76310649 274041.74628285 182963.50789664 204866.19537412
 211233.14161608 148140.89338719 143287.88656169 124437.32791152
  87185.01439017 212627.7687612  115131.38561771 154623.08139036
 258455.2016873  199665.44343723 284344.16068921 160738.26538687
 275313.90578729 198492.14716727 279353.71504658 213841.42043153
 177679.51209358 279418.21006309 256926.75935271 256208.75998203
 233365.60238903 133115.85342695 195256.15838889 187552.62608164
 167594.12169539 149525.23188233 253987.01724604 179263.38109565
 254021.63159712 215545.32434024 191478.06540082  60191.33474048
 161542.09150795 119717.27398993 340323.98859883 183101.41234002
 137777.92946022 109972.46300707 239931.70159838 206602.31933145
 143157.12251477 205420.25052908 134714.73388872 197029.66440319
 150998.38397927 318125.88657587 131817.4783244  158697.87504845
 270482.55068387 114613.89841362 165665.56772035  91188.30651014
 180382.808603   153052.31018382 145910.54943245 157911.47982548
 225462.22839854 235562.7766749  122866.02675918 200989.96458258
 134869.2348763  133634.97499466 119708.07050274 152070.72451672
 158989.35371066 177835.93764964 225970.75411245 147310.38528973
 197829.47496179 238054.55872834 242342.80806223 197030.20259284
 125088.52755396 160000.33752485 225711.01469692 163737.35285328
 225106.82328117 155599.07895409 146116.08736959 165628.23682256
 126064.58304505 107874.76136832  68753.50878434 123790.25517415
 113435.07309568 108334.07533413  88416.22237724 154605.19686996
 185319.23549647 185412.12766024 225077.49112131 103372.26362837
 185060.26928703 200861.93770619 131856.19167728 223238.54796208
 189542.8745475  121682.09620383  95660.37903121 233614.63984392
  76927.69119063 151295.16696057 300484.22735059 216975.63673921]
score is 0.690883755050757

/Users/kazukiegusa/.pyenv/versions/anaconda3-5.3.0/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)